### PR TITLE
Migrate CI from Travis to Github Actions

### LINKED ISSUE #70: Migrate CI from Travis to Github Actions

### PR DESCRIPTION
**Pull request by heuermh**
Fixes #70

### CODE REVIEW

**Comment by josemduarte** [comment]
Yes setting github actions CI can be complicated. It took me forever to get it running in biojava... 

Did you check the protected branch settings? That's also necessary for PRs to run the tests I believe. This is how it looks like in biojava:
Screen Shot 2021-11-17 at 21 57 57

**Comment by heuermh** [comment]
If I look there it says no status checks found.  I am guessing it is a permissions issue, pull request from a fork against an organizational repository ... although I also enabled Github Actions for our bigdatagenomics repositories recently and didn't run into this.

https://github.com/bigdatagenomics/adam/pull/2311

**Comment by josemduarte** [comment]
> If I look there it says no status checks found. 

That's something I also encountered and struggled with. They weren't there but eventually the available status checks appeared. 

My theory is that the system becomes aware of them only when the CI pipeline has actually run somewhere else (e.g. in a push to master).

**Comment by heuermh** [comment]
Hmm, that's also what I was thinking.  I'll try merging this pull request and see if that kicks anything.

**Comment by heuermh** [comment]
The Deploy Snapshot workflow was triggered on merge

https://github.com/biojava/biojava-legacy/actions/runs/1477681785

Guess I'll need to find some bug to fix so that I can create a new pull request 😉

**Pull request merged**
